package priv.simon.oauth2.authresourceserver;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.jwt.Jwt;
import org.springframework.security.jwt.JwtHelper;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class AuthResourceServerApplicationTests {

  @Test
  public void contextLoads() {
    String token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXN0IjoiaGVsbG8iLCJzY29wZSI6WyJ0ZXN0Il0sImRldGFpbHMiOnsicmVtb3RlQWRkcmVzcyI6IjA6MDowOjA6MDowOjA6MSIsInNlc3Npb25JZCI6IjM0QjE4OUVBNkYxREE0ODM0RTVBRUEzMUU5MUEyNDYwIn0sImV4cCI6MTU0MjI3NzExNSwidXNlck5hbWUiOiJhZG1pbiIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJVU0VSIn1dLCJqdGkiOiI4ZTRhNzJkMy1hZmZiLTQ5NzctYjE3NC1jYjllZTRmMmUwOGIiLCJjbGllbnRfaWQiOiJjbGllbnQxIn0.aszoP7crZZRmCdHxO_tuIfnd9FdCMIcI1z1SGygYL0WTjapiA35LH3LnZzX0QmtdqrUGr9mP1Pl5YmNoAYVibd7GSkB1P7vSd251gut7IrmTV3_wL7rj-zR4pfMHF5NhIHbG4FKtXM3E_l93I0IbJGx8t8tCg8N4mGsKHTe0Ht6IjdUT2ET8iohuQ_6XAwEvhRlcJah420G5v4tVQP7eHnZmoFkB1bJ0mXI0Knq-4lFS1xkmIv8qctxQJt6Oin6c4zRHTMvOC4DfknbyDAUy31XLYkFr-7cyy46Nt93E3iPRCNFJRsFybdjVm9S3SI5iPpsw1JRyfyv9iQG17ystaA";
    Jwt jwt = JwtHelper.decode(token);
    System.err.println(jwt.toString());
  }

}
